import { z } from 'zod'

export const envSchema = z.object({
  NODE_ENV: z.enum(['local', 'development', 'production']).default('local'),
  HOST: z.string().default('localhost'),
  PORT: z.coerce.number().default(8000),
  TARGET_URL: z.string().optional(),
  PLAYWRIGHT_BROWSER: z.string().optional(),
  PLAYWRIGHT_HEADLESS: z.string().optional(),
  PLAYWRIGHT_KEEP_OPEN: z.string().optional(),
  PLAYWRIGHT_STORAGE_PATH: z.string().optional(),
  PLAYWRIGHT_USER_DATA_DIR: z.string().optional(),
  PLAYWRIGHT_NAVIGATION_TIMEOUT_MS: z.string().optional(),
  PLAYWRIGHT_TIKTOK_BROWSER_CHANNEL: z.string().optional(),
  OLLAMA_BASE_URL: z.string().optional(),
  OLLAMA_MODEL: z.string().optional(),
  OLLAMA_TIMEOUT_MS: z.string().optional(),
  OLLAMA_INSECURE_TLS: z.string().optional(),
  FACEBOOK_OCR_URL: z.string().optional(),
  FACEBOOK_OCR_TOKEN: z.string().optional(),
  FACEBOOK_COOKIES_PATH: z.string().optional(),
  FACEBOOK_OCR_MODEL: z.string().optional(),
  FACEBOOK_EMAIL: z.string().optional(),
  FACEBOOK_PASSWORD: z.string().optional(),
  FACEBOOK_OCR_ENABLE_SCROLL: z.string().optional(),
  FACEBOOK_COOKIES_HEADLESS: z.string().optional(),
  FACEBOOK_COOKIES_HEADFUL: z.string().optional(),
  FACEBOOK_OCR_TIMEOUT: z.string().optional(),
  FACEBOOK_OCR_DEFAULT_URL: z.string().optional(),
  X_AUTH_TOKEN: z.string().optional(),
  X_CT0_TOKEN: z.string().optional(),
  SOCIAL_SCRAPER_API_KEY: z.string().optional(),
})
